### ISSUE TITLE
TypeError: iconsFromSettings.forEach is not a function

### ISSUE THREAD

**Issue by zipang** [nicholasodo/craft-iconic#1]
This happened after i reordered the icon definition list in the plugin's settings.
As we can see in the developper tools : iconsFromSettings is not an array anymore but an object with numeric keys "1", "0" !  
![capture d ecran 2017-05-29 a 13 15 38](https://cloud.githubusercontent.com/assets/658082/26548649/82469b58-4475-11e7-8518-1ebae65dbdfd.png)

**Comment by nicholasodonnell** [comment]
Thank you very much for both your pull requests. I merged them into master and changed the version from `v1.0.4` to `v1.0.5`.  With the update, I added a check to cast the `iconsFromSettings` variable to an array when re-ordering caused it to be an object.
